// apps/web/src/components/post/TiptapEditor.tsx
import { nodes } from '@kosmo/tiptap';
import { EditorContent, JSONContent, useEditor } from '@tiptap/react';
import { useTranslation } from 'react-i18next';
import { cn } from 'tailwind-variants';
import { Keymap } from '@/lib/tiptap/extensions/keymap';
import { Placeholder } from '@/lib/tiptap/extensions/placeholder';

type Props = {
  className?: string;
  onUpdate?: (content: JSONContent) => void;
};

export default function TiptapEditor({ className, onUpdate }: Props) {
  const { t } = useTranslation('post');

  const editor = useEditor({
    extensions: [
      ...nodes,
      Placeholder.configure({
        placeholder: t('write.placeholder'),
      }),
      Keymap,
    ],

    immediatelyRender: false,
    content: '',

    editorProps: {
      attributes: {
        class: cn('touch-pan-y select-none outline-none', className) ?? '',
      },
    },

    onUpdate({ editor }) {
      onUpdate?.(editor.getJSON());
    },
  });

  if (!editor) {
    return <div className={className}></div>;
  }

  return <EditorContent editor={editor} />;
}

// apps/web/src/lib/tiptap/TiptapEditor.svelte
<script lang="ts">
  import { nodes } from '@kosmo/tiptap';
  import { Editor } from '@tiptap/core';
  import { onDestroy, onMount } from 'svelte';
  import { i18n } from '$lib/i18n.svelte';
  import { Keymap } from './extensions/keymap';
  import { Placeholder } from './extensions/placeholder';
  import type { EditorView } from '@tiptap/pm/view';

  type Props = {
    class?: string;
    editor?: Editor;
    onkeydown?: (view: EditorView, event: KeyboardEvent) => void;
  };

  let { class: className, editor = $bindable(), onkeydown }: Props = $props();

  let element: HTMLElement | undefined = $state(undefined);

  onMount(() => {
    editor = new Editor({
      element: element,
      extensions: [
        ...nodes,
        Placeholder.configure({ placeholder: $i18n('post.write.placeholder') }),
        Keymap,
      ],
      content: '',

      editorProps: {
        attributes: {
          class: 'h-full min-h-24 touch-none select-none outline-none',
        },

        handleKeyDown: onkeydown,
      },

      onTransaction: (e) => {
        editor = e.editor;
      },
    });
  });

  onDestroy(() => {
    editor?.destroy();
  });
</script>

<div bind:this={element} class={className}></div>
