// apps/web/src/routes/(tabs)/search/+page.svelte
<section class="w-[min(100%,36rem)]">
  <p class="text-muted-foreground mb-3 text-xs font-semibold tracking-[1.6px] uppercase">KOSMO</p>
  <h1 class="text-foreground m-0 text-5xl leading-[44px] font-bold">검색</h1>
  <span class="text-secondary-foreground mt-3 block max-w-90 text-base leading-6">
    사용자와 콘텐츠를 빠르게 검색합니다.
  </span>
</section>

// apps/expo/src/app/(tabs)/search.tsx
import { Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function SearchScreen() {
  return (
    <View className="bg-background flex-1">
      <SafeAreaView className="flex-1 justify-center gap-3 px-6" edges={['top']}>
        <Text className="text-muted-foreground text-xs font-semibold tracking-[1.6px] uppercase">
          KOSMO
        </Text>
        <Text className="text-foreground text-5xl leading-[44px] font-bold">검색</Text>
        <Text className="text-secondary-foreground max-w-90 text-base leading-6">
          사용자와 콘텐츠를 빠르게 검색합니다.
        </Text>
      </SafeAreaView>
    </View>
  );
}
