// apps/app/src/components/post/PostList.tsx
import { StyleSheet, Text, View } from 'react-native';
import { graphql, useFragment } from 'react-relay';
import { Button } from '@/components/ui/Button';
import { Skeleton } from '@/components/ui/StateView';
import { useTheme } from '@/theme/ThemeProvider';
import { radii, spacing, typography } from '@/theme/tokens';
import { PostListItem } from './PostListItem';
import type { PostList_homeTimeline$key } from './__generated__/PostList_homeTimeline.graphql';
import type { PostList_profile$key } from './__generated__/PostList_profile.graphql';

const PostListProfileFragment = graphql`
  fragment PostList_profile on Profile {
    id
    posts(first: 20) {
      edges {
        cursor
        node {
          id
          ...PostListItem_post
        }
      }
    }
  }
`;

const PostListHomeTimelineFragment = graphql`
  fragment PostList_homeTimeline on PostConnection {
    edges {
      cursor
      node {
        id
        ...PostListItem_post
      }
    }
  }
`;

type Props = {
  canBookmark?: boolean;
  error?: boolean;
  homeTimeline?: PostList_homeTimeline$key | null;
  loading?: boolean;
  onRetry?: () => void;
  profile?: PostList_profile$key | null;
};

export function PostList({
  canBookmark = false,
  error = false,
  homeTimeline: timelineKey,
  loading = false,
  onRetry,
  profile: profileKey,
}: Props) {
  const profile = useFragment(PostListProfileFragment, profileKey ?? null);
  const timeline = useFragment(PostListHomeTimelineFragment, timelineKey ?? null);
  const edges = timeline?.edges ?? profile?.posts.edges ?? [];
  const hasData = Boolean(timeline || profile);

  if (loading && !hasData) {
    return <PostListSkeleton />;
  }

  if (error && !hasData) {
    return (
      <PostListState
        alert
        description="잠시 후 다시 시도해주세요."
        onRetry={onRetry}
        title="게시글 목록을 불러오지 못했어요"
      />
    );
  }

  if (edges.length === 0) {
    return (
      <PostListState
        description="첫 게시글이 올라오면 여기에 표시돼요."
        title="아직 게시글이 없어요"
      />
    );
  }

  return (
    <View style={styles.root}>
      {edges.map((edge) => (
        <PostListItem canBookmark={canBookmark} key={edge.cursor} post={edge.node} />
      ))}
    </View>
  );
}

function PostListSkeleton() {
  const theme = useTheme();

  return (
    <View>
      <View accessibilityElementsHidden importantForAccessibility="no-hide-descendants">
        {[0, 1, 2].map((item) => (
          <View key={item} style={[styles.skeletonItem, { borderColor: theme.border }]}>
            <View
              style={[
                styles.avatarSkeleton,
                { backgroundColor: theme.surface, borderColor: theme.border },
              ]}
            />
            <View style={styles.skeletonCopy}>
              <View style={styles.skeletonHeader}>
                <Skeleton height={12} width={160} />
                <Skeleton height={12} width={80} />
              </View>
              <View style={styles.skeletonBody}>
                <Skeleton height={12} />
                <Skeleton height={12} />
                <Skeleton height={12} width="70%" />
              </View>
            </View>
          </View>
        ))}
      </View>
      <Text accessibilityLiveRegion="polite" style={styles.srOnly}>
        게시글 목록을 불러오는 중입니다.
      </Text>
    </View>
  );
}

function PostListState({
  alert = false,
  description,
  onRetry,
  title,
}: {
  alert?: boolean;
  description: string;
  onRetry?: () => void;
  title: string;
}) {
  const theme = useTheme();

  return (
    <View accessibilityRole={alert ? 'alert' : undefined} style={styles.state}>
      <Text style={[styles.stateTitle, { color: theme.text }]}>{title}</Text>
      <Text style={[styles.stateDescription, { color: theme.textSecondary }]}>{description}</Text>
      {onRetry ? (
        <Button onPress={onRetry} style={styles.retry} tone="secondary">
          다시 시도
        </Button>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  root: { width: '100%' },
  skeletonItem: {
    alignItems: 'flex-start',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    paddingBottom: spacing.lg,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.sm,
  },
  avatarSkeleton: { borderRadius: radii.full, borderWidth: 1, height: 48, width: 48 },
  skeletonCopy: { flex: 1, minWidth: 0 },
  skeletonHeader: { gap: spacing.sm },
  skeletonBody: { gap: 10, marginTop: spacing.md },
  state: { alignItems: 'center', paddingHorizontal: spacing.lg, paddingVertical: spacing.xxxl },
  stateTitle: { fontFamily: 'SUIT', fontWeight: '700', textAlign: 'center', ...typography.md },
  stateDescription: {
    fontFamily: 'SUIT',
    marginTop: spacing.xs,
    textAlign: 'center',
    ...typography.sm,
  },
  retry: { marginTop: spacing.lg },
  srOnly: {
    height: 1,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    top: 0,
    width: 1,
  },
});

// apps/web/src/lib/components/PostList.svelte
<script lang="ts">
  import { graphql } from '$mearie';
  import { createFragment } from '@mearie/svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  import type { PostList_homeTimeline$key, PostList_profile$key } from '$mearie';

  import PostListItem from './PostListItem.svelte';
  import TextSkeleton from './TextSkeleton.svelte';

  // 프로필 게시글 목록과 홈 타임라인은 같은 Post connection 항목 표현을 쓴다.
  // Pagination UI는 별도 이슈로 분리하고 첫 페이지만 조회한다.
  // 항목 본문은 PostListItem의 TipTap 렌더러 fragment를 통해 렌더한다.
  type Props = HTMLAttributes<HTMLElement> & {
    homeTimeline?: PostList_homeTimeline$key | null;
    profile?: PostList_profile$key | null;
    loading?: boolean;
    error?: boolean;
    onRetry?: () => void;
  };

  let {
    homeTimeline = null,
    profile = null,
    loading = false,
    error = false,
    onRetry,
    class: className,
    ...attributes
  }: Props = $props();

  const profileFragment = createFragment(
    graphql(`
      fragment PostList_profile on Profile {
        id
        posts(first: 20) {
          edges {
            cursor
            node {
              id
              ...PostListItem_post
            }
          }
        }
      }
    `),
    () => profile,
  );

  const homeTimelineFragment = createFragment(
    graphql(`
      fragment PostList_homeTimeline on PostConnection {
        edges {
          cursor
          node {
            id
            ...PostListItem_post
          }
        }
      }
    `),
    () => homeTimeline,
  );

  const postEdges = $derived(
    homeTimelineFragment.data?.edges ?? profileFragment.data?.posts.edges ?? [],
  );
  const hasPostData = $derived(Boolean(homeTimelineFragment.data || profileFragment.data));

  // 첫 화면을 채울 만큼만 반복한다.
  const skeletonItems = [0, 1, 2];
</script>

<section {...attributes} class={className}>
  {#if loading && !hasPostData}
    <div aria-hidden="true">
      {#each skeletonItems as item (item)}
        <div class="border-border flex items-start gap-3 border-b px-2 pt-2 pb-4">
          <div class="w-12 shrink-0">
            <div class="border-border bg-surface size-12 animate-pulse rounded-full border"></div>
          </div>
          <div class="min-w-0 flex-1">
            <div class="flex flex-col gap-2">
              <TextSkeleton width="md" />
              <TextSkeleton width="sm" />
            </div>
            <!-- 실제 게시글(이름 블록 아래 본문이 컬럼 폭으로 흐르는 형태)에 가깝도록
                 본문 줄은 컨테이너 폭을 가득 채운다. -->
            <div class="mt-3 flex flex-col gap-2.5">
              <TextSkeleton width="stretch" />
              <TextSkeleton width="stretch" />
              <TextSkeleton width="lg" />
            </div>
          </div>
        </div>
      {/each}
    </div>
    <span class="sr-only" role="status">게시글 목록을 불러오는 중입니다.</span>
  {:else if error && !hasPostData}
    <div class="px-4 py-12 text-center" role="alert">
      <p class="text-text-primary text-base font-semibold">게시글 목록을 불러오지 못했어요</p>
      <p class="text-text-secondary mt-1 text-sm">잠시 후 다시 시도해주세요.</p>
      {#if onRetry}
        <button
          class="border-border text-text-primary mt-4 rounded-lg border px-4 py-2 text-sm font-bold"
          type="button"
          onclick={onRetry}
        >
          다시 시도
        </button>
      {/if}
    </div>
  {:else if postEdges.length > 0}
    <div>
      {#each postEdges as edge (edge.cursor)}
        <PostListItem post={edge.node} />
      {/each}
    </div>
  {:else}
    <div class="px-4 py-12 text-center">
      <p class="text-text-primary text-base font-semibold">아직 게시글이 없어요</p>
      <p class="text-text-secondary mt-1 text-sm">첫 게시글이 올라오면 여기에 표시돼요.</p>
    </div>
  {/if}
</section>
