// apps/web/src/components/menu/button.tsx
import { Link } from '@tanstack/react-router';
import { AnchorHTMLAttributes, ButtonHTMLAttributes, ComponentType, ReactNode } from 'react';
import { cn } from 'tailwind-variants';

type MenuButtonProps = {
  canCollapse?: boolean;
  visible?: boolean;
  Icon: ComponentType<{ className?: string }>;
  children: ReactNode;
} & (
  | ({ href: string } & AnchorHTMLAttributes<HTMLAnchorElement>)
  | ButtonHTMLAttributes<HTMLButtonElement>
);

export default function MenuButton({
  canCollapse = true,
  visible = true,
  Icon,
  children,
  className,
  ...props
}: MenuButtonProps) {
  return (
    visible &&
    ('href' in props ? (
      <Link
        to={props.href}
        className={cn(
          'hover:bg-muted flex flex-row items-center gap-4 p-4 font-medium',
          className,
          canCollapse ? 'justify-center lg:justify-start' : 'justify-start',
          className,
        )}
        tabIndex={0}
        {...props}
      >
        <Icon className="size-6" />
        <span className={cn('text-lg', canCollapse ? 'sr-only lg:not-sr-only' : 'inline')}>
          {children}
        </span>
      </Link>
    ) : (
      <button
        className={cn(
          'hover:bg-muted flex flex-row items-center gap-4 p-4 font-medium',
          className,
          canCollapse ? 'justify-center lg:justify-start' : 'justify-start',
          className,
        )}
        {...props}
      >
        <Icon className="size-6" />
        <span className={cn('text-lg', canCollapse ? 'sr-only lg:not-sr-only' : 'inline')}>
          {children}
        </span>
      </button>
    ))
  );
}

// apps/admin/src/lib/components/ui/button/button.svelte
<script lang="ts">
  import { tv } from 'tailwind-variants';
  import { resolve } from '$app/paths';
  import type { Snippet } from 'svelte';
  import type { VariantProps } from 'tailwind-variants';
  import type { PathnameWithSearchOrHash } from '$app/types';

  const variants = tv({
    base: 'inline-flex items-center justify-center rounded-lg border text-sm font-medium transition-colors outline-none focus-visible:ring-3 focus-visible:ring-ring/50',
    variants: {
      variant: {
        default: 'border-transparent bg-primary text-primary-foreground hover:bg-primary/80',
        outline: 'border-border bg-background text-foreground hover:bg-muted',
      },
      size: {
        default: 'h-8 px-2.5',
        sm: 'h-7 px-2.5 text-[0.8rem]',
      },
    },
    defaultVariants: { variant: 'default', size: 'default' },
  });

  let {
    children,
    href,
    size = 'default',
    variant = 'default',
  }: {
    children: Snippet;
    href: PathnameWithSearchOrHash;
    size?: VariantProps<typeof variants>['size'];
    variant?: VariantProps<typeof variants>['variant'];
  } = $props();
</script>

<a class={variants({ variant, size })} href={resolve(href)}>
  {@render children()}
</a>
