// apps/web/src/routes/(tabs)/@[handle]/followers/+page.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { createQuery } from '@mearie/svelte';
  import { graphql } from '$mearie';
  import ProfileConnectionList from '$lib/components/ProfileConnectionList.svelte';

  const query = createQuery(
    graphql(`
      query ProfileFollowersPageQuery($handle: String!) {
        currentSession {
          id
          selectedProfile {
            id
          }
        }
        profileByHandle(handle: $handle) {
          id
          ...ProfileConnectionList_followersProfile
        }
      }
    `),
    () => ({ handle: page.params.handle! }),
  );

  const profile = $derived(query.data?.profileByHandle ?? null);
  const viewerProfileId = $derived(query.data?.currentSession?.selectedProfile?.id ?? null);
</script>

<ProfileConnectionList
  kind="followers"
  followersProfile={profile}
  {viewerProfileId}
  loading={query.loading}
  error={Boolean(query.error)}
  onRetry={query.refetch}
/>

// apps/app/src/app/(tabs)/(profile)/[profileHandle]/followers.tsx
import { useState } from 'react';
import { graphql, useLazyLoadQuery } from 'react-relay';
import {
  ProfileConnectionList,
  ProfileConnectionListState,
} from '@/components/profile/ProfileConnectionList';
import { useProfileHandle } from '@/components/profile/route';
import { RouteBoundary } from '@/components/RouteBoundary';
import { useRelayActor } from '@/relay/RelayActorProvider';
import type { ProfileFollowersPageQuery as ProfileFollowersPageQueryType } from './__generated__/ProfileFollowersPageQuery.graphql';

const ProfileFollowersPageQuery = graphql`
  query ProfileFollowersPageQuery($handle: String!) {
    profileByHandle(handle: $handle) {
      id
      ...ProfileConnectionList_followersProfile
    }
  }
`;

export default function ProfileFollowersPage() {
  const handle = useProfileHandle();
  const { revision } = useRelayActor();
  const [fetchKey, setFetchKey] = useState(0);

  return (
    <RouteBoundary
      error={(retry) => (
        <ProfileConnectionListState kind="followers" onRetry={retry} state="error" />
      )}
      key={handle}
      loading={<ProfileConnectionListState kind="followers" state="loading" />}
      onRetry={() => setFetchKey((key) => key + 1)}
      title="팔로워 목록을 불러오지 못했어요"
    >
      <ProfileFollowersPageContent fetchKey={`${revision}:${fetchKey}`} handle={handle} />
    </RouteBoundary>
  );
}

function ProfileFollowersPageContent({ fetchKey, handle }: { fetchKey: string; handle: string }) {
  const data = useLazyLoadQuery<ProfileFollowersPageQueryType>(
    ProfileFollowersPageQuery,
    { handle },
    { fetchKey, fetchPolicy: 'store-and-network' },
  );

  return data.profileByHandle ? (
    <ProfileConnectionList kind="followers" profile={data.profileByHandle} />
  ) : null;
}
