// apps/expo/src/app/(tabs)/index.tsx
import { useQuery } from '@mearie/react';
import { Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { graphql } from '$mearie';

export default function HomeScreen() {
  const { data, loading } = useQuery(
    graphql(`
      query TestQuery {
        me {
          id
          name
        }
      }
    `),
  );

  return (
    <View className="bg-background flex-1">
      <SafeAreaView className="flex-1 justify-center gap-3 px-6" edges={['top']}>
        <Text className="text-primary text-xs font-semibold tracking-[1.6px] uppercase">KOSMO</Text>
        <Text className="text-foreground text-5xl leading-[44px] font-bold">홈</Text>
        <Text className="text-secondary-foreground max-w-90 text-base leading-6">
          피드를 확인하고 새로운 소식을 탐색합니다.
        </Text>
        {loading ? <Text>Loading...</Text> : <Text>{data?.me?.name}</Text>}
      </SafeAreaView>
    </View>
  );
}

// apps/web/src/routes/(tabs)/+page.svelte
<script lang="ts">
  import { createQuery } from '@mearie/svelte';
  import { graphql } from '$mearie';

  const query = createQuery(
    graphql(`
      query TestQuery {
        me {
          id
          name
        }
      }
    `),
  );
</script>

<section class="w-[min(100%,36rem)]">
  <p class="text-primary mb-3 text-xs font-semibold tracking-[1.6px] uppercase">KOSMO</p>
  <h1 class="text-foreground m-0 text-5xl leading-[44px] font-bold">홈</h1>
  <span class="text-secondary-foreground mt-3 block max-w-90 text-base leading-6">
    피드를 확인하고 새로운 소식을 탐색합니다.
  </span>
  <p class="text-foreground mt-3 text-base">
    {query.loading ? 'Loading...' : query.data?.me?.name}
  </p>
</section>
