// apps/web/src/lib/components/FollowButton.svelte
<script lang="ts">
  import { createFragment, createMutation } from '@mearie/svelte';
  import { graphql } from '$mearie';
  import type { FollowButton_profile$key } from '$mearie';

  import Button from './Button.svelte';

  const followButtonProfileFragment = graphql(`
    fragment FollowButton_profile on Profile {
      id
      origin
      viewerState {
        isSelf
        follow {
          id
        }
      }
    }
  `);

  type Props = {
    profile: FollowButton_profile$key;
    size?: 'sm' | 'md' | 'lg';
    class?: string;
  };

  // followee/profile에 viewerState와 followersCount를 함께 선택해, mutation 응답만으로
  // normalized cache의 Profile.viewerState / followersCount가 갱신되게 한다(별도 refetch 불필요).
  const followProfileMutation = graphql(`
    mutation FollowButtonFollowProfile($id: ID!) {
      followProfile(input: { id: $id }) {
        profileFollow {
          id
          followee {
            followersCount
            ...FollowButton_profile
          }
        }
      }
    }
  `);

  const unfollowProfileMutation = graphql(`
    mutation FollowButtonUnfollowProfile($id: ID!) {
      unfollowProfile(input: { id: $id }) {
        profileFollowId
        profile {
          followersCount
          ...FollowButton_profile
        }
      }
    }
  `);

  let { profile, size = 'sm', class: className = '' }: Props = $props();

  const [followProfile] = createMutation(followProfileMutation);
  const [unfollowProfile] = createMutation(unfollowProfileMutation);
  const profileFragment = createFragment(followButtonProfileFragment, () => profile);

  let loading = $state(false);
  let errorMessage = $state<string | null>(null);

  const viewerState = $derived(profileFragment.data.viewerState);
  const viewerFollow = $derived(viewerState?.follow ?? null);
  const isLocalProfile = $derived(profileFragment.data.origin === 'LOCAL');
  const isFollowing = $derived(Boolean(viewerFollow));
  const disabled = $derived(loading);

  const toggleFollow = async () => {
    if (disabled || !isLocalProfile || !viewerState || viewerState.isSelf) {
      return;
    }

    const targetProfileId = profileFragment.data.id;

    loading = true;
    errorMessage = null;

    try {
      if (isFollowing) {
        await unfollowProfile({ id: targetProfileId });
        return;
      }

      await followProfile({ id: targetProfileId });
    } catch {
      errorMessage = '팔로우 상태를 변경하지 못했습니다.';
    } finally {
      loading = false;
    }
  };
</script>

{#if isLocalProfile && viewerState && !viewerState.isSelf}
  <div class={`inline-flex flex-col items-end gap-1 ${className}`}>
    <Button
      variant={isFollowing ? 'secondary' : 'primary'}
      {size}
      {disabled}
      aria-busy={loading}
      aria-pressed={isFollowing}
      onclick={toggleFollow}
    >
      {loading ? '처리 중' : isFollowing ? '팔로잉' : '팔로우'}
    </Button>
    {#if errorMessage}
      <p class="text-text-secondary m-0 max-w-56 text-right text-xs leading-4" role="alert">
        {errorMessage}
      </p>
    {/if}
  </div>
{/if}

// apps/app/src/components/profile/FollowButton.tsx
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { graphql, useFragment, useMutation } from 'react-relay';
import { ConnectionHandler } from 'relay-runtime';
import { Button } from '@/components/ui/Button';
import { useTheme } from '@/theme/ThemeProvider';
import { spacing, typography } from '@/theme/tokens';
import type { StyleProp, ViewStyle } from 'react-native';
import type { FollowButton_profile$key } from './__generated__/FollowButton_profile.graphql';
import type { FollowButtonFollowProfileMutation } from './__generated__/FollowButtonFollowProfileMutation.graphql';
import type { FollowButtonUnfollowProfileMutation } from './__generated__/FollowButtonUnfollowProfileMutation.graphql';

type FollowButtonProps = {
  profile: FollowButton_profile$key;
  style?: StyleProp<ViewStyle>;
};

const followButtonProfileFragment = graphql`
  fragment FollowButton_profile on Profile {
    id
    instance {
      kind
    }
    viewerState {
      isSelf
      follow {
        id
        follower {
          id
        }
      }
    }
  }
`;

const followProfileMutation = graphql`
  mutation FollowButtonFollowProfileMutation($id: ID!) {
    followProfile(input: { id: $id }) {
      profileFollow {
        id
      }
      followerProfile {
        id
        followingCount
      }
      followeeProfile {
        id
        followersCount
        ...FollowButton_profile
      }
    }
  }
`;

const unfollowProfileMutation = graphql`
  mutation FollowButtonUnfollowProfileMutation($connections: [ID!]!, $id: ID!) {
    unfollowProfile(input: { id: $id }) {
      profileFollowId @deleteEdge(connections: $connections)
      followerProfile {
        id
        followingCount
      }
      followeeProfile {
        id
        followersCount
        ...FollowButton_profile
      }
    }
  }
`;

export function FollowButton({ profile, style }: FollowButtonProps) {
  const theme = useTheme();
  const data = useFragment(followButtonProfileFragment, profile);
  const [commitFollow, following] =
    useMutation<FollowButtonFollowProfileMutation>(followProfileMutation);
  const [commitUnfollow, unfollowing] =
    useMutation<FollowButtonUnfollowProfileMutation>(unfollowProfileMutation);
  const [error, setError] = useState(false);
  const viewerState = data.viewerState;
  const isLocalProfile = data.instance.kind === 'LOCAL';
  const isFollowing = Boolean(viewerState?.follow);
  const loading = following || unfollowing;

  if (!isLocalProfile || !viewerState || viewerState.isSelf) {
    return null;
  }

  const toggleFollow = () => {
    if (loading || !isLocalProfile) {
      return;
    }

    setError(false);
    const callbacks = {
      onCompleted: (_response: unknown, errors: ReadonlyArray<unknown> | null | undefined) =>
        setError(Boolean(errors?.length)),
      onError: () => setError(true),
    };

    if (isFollowing) {
      const followerId = viewerState.follow?.follower?.id;
      const connections = [
        ConnectionHandler.getConnectionID(data.id, 'ProfileConnectionList_followers'),
        ...(followerId
          ? [ConnectionHandler.getConnectionID(followerId, 'ProfileConnectionList_following')]
          : []),
      ];

      commitUnfollow({ ...callbacks, variables: { connections, id: data.id } });
    } else {
      commitFollow({ ...callbacks, variables: { id: data.id } });
    }
  };

  return (
    <View style={[styles.root, style]}>
      <Button
        aria-pressed={isFollowing}
        accessibilityState={{ busy: loading, disabled: loading, selected: isFollowing }}
        disabled={loading}
        hitSlop={6}
        onPress={toggleFollow}
        style={styles.button}
        tone={isFollowing ? 'secondary' : 'primary'}
      >
        {loading ? '처리 중' : isFollowing ? '팔로잉' : '팔로우'}
      </Button>
      {error ? (
        <Text accessibilityRole="alert" style={[styles.error, { color: theme.textSecondary }]}>
          팔로우 상태를 변경하지 못했습니다.
        </Text>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  root: { alignItems: 'flex-end', gap: spacing.xs },
  button: { minHeight: 32, paddingVertical: 0 },
  error: { fontFamily: 'SUIT', maxWidth: 224, textAlign: 'right', ...typography.xsm },
});
