// apps/web/src/lib/components/ProfileConnectionList.svelte
<script lang="ts">
  import { createFragment } from '@mearie/svelte';
  import { graphql } from '$mearie';
  import type { HTMLAttributes } from 'svelte/elements';

  import type {
    ProfileConnectionList_followersProfile$key,
    ProfileConnectionList_followingProfile$key,
    ProfileListItem_profile$key,
  } from '$mearie';

  import ProfileListItem from './ProfileListItem.svelte';
  import TextSkeleton from './TextSkeleton.svelte';

  // 프로필 팔로워/팔로잉 목록 영역. 게시글 목록(PostList)과 같은 상태(로딩/오류/빈) 표현·접근성 패턴을 따른다.
  // 팔로워/팔로잉은 같은 컴포넌트를 `kind`로 분기해 시각/상태 구조를 일치시킨다.
  type ConnectionKind = 'followers' | 'following';
  type ConnectionProfileItem = { cursor: string; profile: ProfileListItem_profile$key };

  type Props = HTMLAttributes<HTMLElement> & {
    kind: ConnectionKind;
    followersProfile?: ProfileConnectionList_followersProfile$key | null;
    followingProfile?: ProfileConnectionList_followingProfile$key | null;
    additionalProfiles?: ConnectionProfileItem[];
    hasNextPage?: boolean | null;
    endCursor?: string | null;
    loadingNextPage?: boolean;
    nextPageError?: boolean;
    loading?: boolean;
    error?: boolean;
    onRetry?: () => void;
    onLoadMore?: (after: string) => void;
  };

  let {
    kind,
    followersProfile = null,
    followingProfile = null,
    additionalProfiles = [],
    hasNextPage = null,
    endCursor = null,
    loadingNextPage = false,
    nextPageError = false,
    loading = false,
    error = false,
    onRetry,
    onLoadMore,
    class: className,
    ...attributes
  }: Props = $props();

  // 목록 종류별 표시 문구를 컴포넌트 안에 모아 두 라우트가 같은 카피를 공유하게 한다.
  const copy: Record<
    ConnectionKind,
    {
      title: string;
      emptyTitle: string;
      emptyDescription: string;
      errorTitle: string;
      loadingLabel: string;
      nextPageErrorTitle: string;
      loadingNextPageLabel: string;
    }
  > = {
    followers: {
      title: '팔로워',
      emptyTitle: '아직 팔로워가 없어요',
      emptyDescription: '이 프로필을 팔로우하는 사람이 생기면 여기에 표시돼요.',
      errorTitle: '팔로워 목록을 불러오지 못했어요',
      loadingLabel: '팔로워 목록을 불러오는 중입니다.',
      nextPageErrorTitle: '팔로워를 더 불러오지 못했어요',
      loadingNextPageLabel: '팔로워를 더 불러오는 중입니다.',
    },
    following: {
      title: '팔로잉',
      emptyTitle: '아직 팔로잉이 없어요',
      emptyDescription: '이 프로필이 팔로우하는 사람이 생기면 여기에 표시돼요.',
      errorTitle: '팔로잉 목록을 불러오지 못했어요',
      loadingLabel: '팔로잉 목록을 불러오는 중입니다.',
      nextPageErrorTitle: '팔로잉을 더 불러오지 못했어요',
      loadingNextPageLabel: '팔로잉을 더 불러오는 중입니다.',
    },
  };

  const text = $derived(copy[kind]);

  const followersFragment = createFragment(
    graphql(`
      fragment ProfileConnectionList_followersProfile on Profile {
        id
        followers(first: 20) {
          pageInfo {
            hasNextPage
            endCursor
          }
          edges {
            cursor
            node {
              id
              follower {
                id
                ...ProfileListItem_profile
              }
            }
          }
        }
      }
    `),
    () => followersProfile,
  );

  const followingFragment = createFragment(
    graphql(`
      fragment ProfileConnectionList_followingProfile on Profile {
        id
        following(first: 20) {
          pageInfo {
            hasNextPage
            endCursor
          }
          edges {
            cursor
            node {
              id
              followee {
                id
                ...ProfileListItem_profile
              }
            }
          }
        }
      }
    `),
    () => followingProfile,
  );

  const getConnectionProfiles = () => {
    if (kind === 'followers') {
      return (
        followersFragment.data?.followers.edges.flatMap((edge) =>
          edge.node.follower ? [{ cursor: edge.cursor, profile: edge.node.follower }] : [],
        ) ?? []
      );
    }

    return (
      followingFragment.data?.following.edges.flatMap((edge) =>
        edge.node.followee ? [{ cursor: edge.cursor, profile: edge.node.followee }] : [],
      ) ?? []
    );
  };

  const firstPageProfiles = $derived(getConnectionProfiles());
  const connectionProfiles = $derived([...firstPageProfiles, ...additionalProfiles]);
  const hasConnectionData = $derived(
    kind === 'followers' ? Boolean(followersFragment.data) : Boolean(followingFragment.data),
  );
  const firstPageInfo = $derived(
    kind === 'followers'
      ? followersFragment.data?.followers.pageInfo
      : followingFragment.data?.following.pageInfo,
  );
  const effectiveHasNextPage = $derived(hasNextPage ?? firstPageInfo?.hasNextPage ?? false);
  const effectiveEndCursor = $derived(endCursor ?? firstPageInfo?.endCursor ?? null);
  const showPagination = $derived(Boolean(onLoadMore) && (effectiveHasNextPage || nextPageError));
  const canLoadMore = $derived(Boolean(effectiveEndCursor) && !loadingNextPage);

  const loadMore = () => {
    if (!effectiveEndCursor || loadingNextPage) {
      return;
    }

    onLoadMore?.(effectiveEndCursor);
  };

  // 첫 화면을 채울 만큼만 반복한다.
  const skeletonItems = [0, 1, 2];
</script>

<section {...attributes} class={className}>
  <h2 class="text-text-primary border-border border-b px-4 pt-2 pb-3 text-base font-bold">
    {text.title}
  </h2>
  {#if loading && !hasConnectionData}
    <div aria-hidden="true">
      {#each skeletonItems as item (item)}
        <div class="border-border flex items-center gap-3 border-b px-4 py-3">
          <div
            class="border-border bg-surface size-10 shrink-0 animate-pulse rounded-full border"
          ></div>
          <div class="flex min-w-0 flex-1 flex-col gap-2">
            <TextSkeleton width="md" />
            <TextSkeleton width="sm" />
          </div>
        </div>
      {/each}
    </div>
    <span class="sr-only" role="status">{text.loadingLabel}</span>
  {:else if error && !hasConnectionData}
    <div class="px-4 py-12 text-center" role="alert">
      <p class="text-text-primary text-base font-semibold">{text.errorTitle}</p>
      <p class="text-text-secondary mt-1 text-sm">잠시 후 다시 시도해주세요.</p>
      {#if onRetry}
        <button
          class="border-border text-text-primary mt-4 rounded-lg border px-4 py-2 text-sm font-bold"
          type="button"
          onclick={onRetry}
        >
          다시 시도
        </button>
      {/if}
    </div>
  {:else if connectionProfiles.length > 0}
    <div>
      {#each connectionProfiles as item (item.cursor)}
        <ProfileListItem profile={item.profile} linked width="wide" class="w-full" />
      {/each}
    </div>
    {#if showPagination}
      <div class="border-border border-t px-4 py-4 text-center">
        {#if nextPageError}
          <p class="text-text-primary text-sm font-semibold" role="alert">
            {text.nextPageErrorTitle}
          </p>
          <p class="text-text-secondary mt-1 text-sm">잠시 후 다시 시도해주세요.</p>
        {/if}
        <button
          class="border-border text-text-primary mt-3 rounded-lg border px-4 py-2 text-sm font-bold disabled:opacity-45"
          type="button"
          disabled={!canLoadMore}
          aria-busy={loadingNextPage}
          onclick={loadMore}
        >
          {loadingNextPage ? '불러오는 중' : nextPageError ? '다시 시도' : '더 불러오기'}
        </button>
        {#if loadingNextPage}
          <span class="sr-only" role="status">{text.loadingNextPageLabel}</span>
        {/if}
      </div>
    {/if}
  {:else}
    <div class="px-4 py-12 text-center">
      <p class="text-text-primary text-base font-semibold">{text.emptyTitle}</p>
      <p class="text-text-secondary mt-1 text-sm">{text.emptyDescription}</p>
    </div>
  {/if}
</section>

// apps/app/src/components/profile/ProfileConnectionList.tsx
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { graphql, usePaginationFragment } from 'react-relay';
import { Button } from '@/components/ui/Button';
import { Skeleton, StateView } from '@/components/ui/StateView';
import { useTheme } from '@/theme/ThemeProvider';
import { layoutRecipes, spacing, typography } from '@/theme/tokens';
import { ProfileListItem } from './ProfileListItem';
import type { ProfileConnectionList_followersProfile$key } from './__generated__/ProfileConnectionList_followersProfile.graphql';
import type { ProfileConnectionList_followingProfile$key } from './__generated__/ProfileConnectionList_followingProfile.graphql';
import type { ProfileFollowersNextPageQuery } from './__generated__/ProfileFollowersNextPageQuery.graphql';
import type { ProfileFollowingNextPageQuery } from './__generated__/ProfileFollowingNextPageQuery.graphql';

type ConnectionKind = 'followers' | 'following';

type ProfileConnectionListProps =
  | { kind: 'followers'; profile: ProfileConnectionList_followersProfile$key }
  | { kind: 'following'; profile: ProfileConnectionList_followingProfile$key };

const followersFragment = graphql`
  fragment ProfileConnectionList_followersProfile on Profile
  @argumentDefinitions(count: { type: "Int", defaultValue: 20 }, cursor: { type: "String" })
  @refetchable(queryName: "ProfileFollowersNextPageQuery") {
    followers(first: $count, after: $cursor) @connection(key: "ProfileConnectionList_followers") {
      edges {
        cursor
        node {
          id
          follower {
            id
            ...ProfileListItem_profile
          }
        }
      }
    }
  }
`;

const followingFragment = graphql`
  fragment ProfileConnectionList_followingProfile on Profile
  @argumentDefinitions(count: { type: "Int", defaultValue: 20 }, cursor: { type: "String" })
  @refetchable(queryName: "ProfileFollowingNextPageQuery") {
    following(first: $count, after: $cursor) @connection(key: "ProfileConnectionList_following") {
      edges {
        cursor
        node {
          id
          followee {
            id
            ...ProfileListItem_profile
          }
        }
      }
    }
  }
`;

const copy = {
  followers: {
    emptyDescription: '이 프로필을 팔로우하는 사람이 생기면 여기에 표시돼요.',
    emptyTitle: '아직 팔로워가 없어요',
    errorTitle: '팔로워 목록을 불러오지 못했어요',
    loadError: '팔로워를 더 불러오지 못했어요',
    loadingLabel: '팔로워 목록을 불러오는 중입니다.',
    loadingNextLabel: '팔로워를 더 불러오는 중입니다.',
    title: '팔로워',
  },
  following: {
    emptyDescription: '이 프로필이 팔로우하는 사람이 생기면 여기에 표시돼요.',
    emptyTitle: '아직 팔로잉이 없어요',
    errorTitle: '팔로잉 목록을 불러오지 못했어요',
    loadError: '팔로잉을 더 불러오지 못했어요',
    loadingLabel: '팔로잉 목록을 불러오는 중입니다.',
    loadingNextLabel: '팔로잉을 더 불러오는 중입니다.',
    title: '팔로잉',
  },
} as const;

export function ProfileConnectionList(props: ProfileConnectionListProps) {
  return props.kind === 'followers' ? (
    <FollowersList profile={props.profile} />
  ) : (
    <FollowingList profile={props.profile} />
  );
}

export function ProfileConnectionListState({
  kind,
  onRetry,
  state,
}: {
  kind: ConnectionKind;
  onRetry?: () => void;
  state: 'error' | 'loading';
}) {
  const theme = useTheme();
  const text = copy[kind];

  return (
    <View>
      <ConnectionTitle kind={kind} />
      {state === 'loading' ? (
        <>
          <View accessibilityElementsHidden importantForAccessibility="no-hide-descendants">
            {[0, 1, 2].map((item) => (
              <View key={item} style={[styles.skeletonItem, { borderColor: theme.border }]}>
                <Skeleton
                  circular
                  height={40}
                  style={[styles.avatarSkeleton, { borderColor: theme.border }]}
                  width={40}
                />
                <View style={styles.skeletonCopy}>
                  <Skeleton height={12} width={160} />
                  <Skeleton height={12} width={80} />
                </View>
              </View>
            ))}
          </View>
          <Text accessibilityLiveRegion="polite" style={styles.srOnly}>
            {text.loadingLabel}
          </Text>
        </>
      ) : (
        <StateView
          actionLabel={onRetry ? '다시 시도' : undefined}
          alert
          description="잠시 후 다시 시도해주세요."
          onAction={onRetry}
          style={styles.state}
          title={text.errorTitle}
        />
      )}
    </View>
  );
}

function FollowersList({ profile }: { profile: ProfileConnectionList_followersProfile$key }) {
  const pagination = usePaginationFragment<
    ProfileFollowersNextPageQuery,
    ProfileConnectionList_followersProfile$key
  >(followersFragment, profile);
  const profiles = pagination.data.followers.edges.flatMap((edge) =>
    edge.node.follower ? [{ cursor: edge.cursor, profile: edge.node.follower }] : [],
  );

  return (
    <ConnectionList
      hasNext={pagination.hasNext}
      isLoadingNext={pagination.isLoadingNext}
      kind="followers"
      loadNext={pagination.loadNext}
      profiles={profiles}
    />
  );
}

function FollowingList({ profile }: { profile: ProfileConnectionList_followingProfile$key }) {
  const pagination = usePaginationFragment<
    ProfileFollowingNextPageQuery,
    ProfileConnectionList_followingProfile$key
  >(followingFragment, profile);
  const profiles = pagination.data.following.edges.flatMap((edge) =>
    edge.node.followee ? [{ cursor: edge.cursor, profile: edge.node.followee }] : [],
  );

  return (
    <ConnectionList
      hasNext={pagination.hasNext}
      isLoadingNext={pagination.isLoadingNext}
      kind="following"
      loadNext={pagination.loadNext}
      profiles={profiles}
    />
  );
}

type ConnectionListProps = {
  hasNext: boolean;
  isLoadingNext: boolean;
  kind: keyof typeof copy;
  loadNext: (count: number, options?: { onComplete?: (error: Error | null) => void }) => void;
  profiles: ReadonlyArray<{
    cursor: string;
    profile: Parameters<typeof ProfileListItem>[0]['profile'];
  }>;
};

function ConnectionList({ hasNext, isLoadingNext, kind, loadNext, profiles }: ConnectionListProps) {
  const theme = useTheme();
  const [loadError, setLoadError] = useState(false);
  const text = copy[kind];
  const loadMore = () => {
    if (isLoadingNext) {
      return;
    }

    setLoadError(false);
    loadNext(20, { onComplete: (error) => setLoadError(Boolean(error)) });
  };

  return (
    <View>
      <ConnectionTitle kind={kind} />
      {profiles.length ? (
        profiles.map((item) => <ProfileListItem key={item.cursor} linked profile={item.profile} />)
      ) : (
        <StateView
          description={text.emptyDescription}
          style={styles.state}
          title={text.emptyTitle}
        />
      )}
      {hasNext || loadError ? (
        loadError ? (
          <StateView
            actionLabel="다시 시도"
            alert
            description="잠시 후 다시 시도해주세요."
            onAction={loadMore}
            style={[styles.pagination, { borderColor: theme.border }]}
            title={text.loadError}
          />
        ) : (
          <View style={[styles.pagination, { borderColor: theme.border }]}>
            <Button
              accessibilityState={{ busy: isLoadingNext, disabled: isLoadingNext }}
              disabled={isLoadingNext}
              onPress={loadMore}
              style={styles.paginationAction}
              tone="secondary"
            >
              {isLoadingNext ? '불러오는 중' : '더 불러오기'}
            </Button>
            {isLoadingNext ? (
              <Text accessibilityLiveRegion="polite" style={styles.srOnly}>
                {text.loadingNextLabel}
              </Text>
            ) : null}
          </View>
        )
      ) : null}
    </View>
  );
}

function ConnectionTitle({ kind }: { kind: ConnectionKind }) {
  const theme = useTheme();

  return (
    <Text
      accessibilityRole="header"
      style={[styles.title, { borderColor: theme.border, color: theme.text }]}
    >
      {copy[kind].title}
    </Text>
  );
}

const styles = StyleSheet.create({
  title: {
    borderBottomWidth: 1,
    fontFamily: 'SUIT',
    fontWeight: '700',
    paddingBottom: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    ...typography.md,
  },
  state: {
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xxxl,
  },
  pagination: { alignItems: 'center', borderTopWidth: 1, padding: spacing.lg },
  paginationAction: { marginTop: spacing.md },
  skeletonItem: {
    ...layoutRecipes.listRow,
    borderBottomWidth: 1,
  },
  avatarSkeleton: { borderWidth: 1 },
  skeletonCopy: { flex: 1, gap: spacing.sm, minWidth: 0 },
  srOnly: {
    height: 1,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    top: 0,
    width: 1,
  },
});
