// apps/web/src/routes/(tabs)/(protected)/compose/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { graphql } from '$mearie';
  import { createQuery } from '@mearie/svelte';
  import Button from '$lib/components/Button.svelte';
  import PostComposer from '$lib/components/PostComposer.svelte';

  const query = createQuery(
    graphql(`
      query ComposePageQuery {
        currentSession {
          id
          selectedProfile {
            id
            ...PostComposer_profile
          }
        }
      }
    `),
  );

  const selectedProfile = $derived(query.data?.currentSession?.selectedProfile ?? null);
  const loading = $derived(query.loading && !query.data);
  const error = $derived(Boolean(query.error) && !query.data);
</script>

<section class="grid w-[min(100%,36rem)] gap-5 self-start">
  <header>
    <p class="text-text-secondary mb-3 text-xs font-semibold tracking-[1.6px] uppercase">KOSMO</p>
    <h1 class="text-text-primary m-0 text-4xl leading-10 font-bold">글쓰기</h1>
  </header>

  {#if loading}
    <div class="border-border bg-card grid gap-3 rounded-md border p-4" aria-hidden="true">
      <div class="bg-surface h-5 w-36 animate-pulse rounded-sm"></div>
      <div class="bg-surface h-40 animate-pulse rounded-md"></div>
      <div class="flex justify-end">
        <div class="bg-surface h-10 w-30 animate-pulse rounded-sm"></div>
      </div>
    </div>
    <span class="sr-only" role="status">글쓰기 화면을 불러오는 중입니다.</span>
  {:else if error}
    <div class="border-border bg-card rounded-md border p-5" role="alert">
      <p class="text-text-primary m-0 text-base font-bold">글쓰기 정보를 불러오지 못했어요</p>
      <p class="text-text-secondary mt-1 mb-4 text-sm">잠시 후 다시 시도해주세요.</p>
      <Button variant="secondary" onclick={() => query.refetch()}>다시 시도</Button>
    </div>
  {:else if !selectedProfile}
    <div class="border-border bg-card rounded-md border p-5">
      <p class="text-text-primary m-0 text-base font-bold">프로필이 필요해요</p>
      <p class="text-text-secondary mt-1 mb-4 text-sm">
        홈에서 프로필을 만들거나 선택한 뒤 글을 쓸 수 있어요.
      </p>
      <Button variant="secondary" onclick={() => goto('/home')}>홈으로 이동</Button>
    </div>
  {:else}
    <PostComposer profile={selectedProfile} />
  {/if}
</section>

// apps/app/src/app/(tabs)/(protected)/compose.tsx
import { usePathname, useRouter, useSegments } from 'expo-router';
import { Platform, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { graphql, useLazyLoadQuery } from 'react-relay';
import { PageHeader } from '@/components/PageHeader';
import { PostComposer } from '@/components/post/PostComposer';
import { RouteBoundary, useRouteBoundary } from '@/components/RouteBoundary';
import { getWebMobileShellHeader } from '@/components/shell/shellLayout';
import { Button } from '@/components/ui/Button';
import { Skeleton } from '@/components/ui/StateView';
import { useTheme } from '@/theme/ThemeProvider';
import { radii, spacing, typography } from '@/theme/tokens';
import type { ComposePageQuery } from './__generated__/ComposePageQuery.graphql';

const ComposeQuery = graphql`
  query ComposePageQuery {
    currentSession {
      id
      selectedProfile {
        id
        ...PostComposer_profile
      }
    }
  }
`;

export default function ComposeScreen() {
  const pathname = usePathname();
  const routeSegments = useSegments();
  const router = useRouter();
  const { width } = useWindowDimensions();
  const shellOwnsHeader =
    getWebMobileShellHeader(Platform.OS === 'web', width, pathname, routeSegments)?.title ===
    '글쓰기';

  return (
    <ScrollView contentContainerStyle={styles.root} keyboardShouldPersistTaps="handled">
      {shellOwnsHeader ? null : <PageHeader title="글쓰기" />}
      <View style={styles.content}>
        <RouteBoundary
          error={(retry) => (
            <ComposeStateCard
              alert
              description="잠시 후 다시 시도해주세요."
              onAction={retry}
              title="글쓰기 정보를 불러오지 못했어요"
            />
          )}
          loading={<ComposeLoading />}
          title="글쓰기 정보를 불러오지 못했어요"
        >
          <ComposeContent onGoHome={() => router.push('/home')} />
        </RouteBoundary>
      </View>
    </ScrollView>
  );
}

function ComposeContent({ onGoHome }: { onGoHome: () => void }) {
  const { fetchKey } = useRouteBoundary();
  const data = useLazyLoadQuery<ComposePageQuery>(
    ComposeQuery,
    {},
    { fetchKey, fetchPolicy: 'store-or-network' },
  );
  const profile = data.currentSession?.selectedProfile ?? null;

  return profile ? (
    <PostComposer profile={profile} />
  ) : (
    <ComposeStateCard
      description="홈에서 프로필을 만들거나 선택한 뒤 글을 쓸 수 있어요."
      onAction={onGoHome}
      title="프로필이 필요해요"
    />
  );
}

function ComposeLoading() {
  const theme = useTheme();

  return (
    <>
      <View
        accessibilityElementsHidden
        style={[styles.loadingCard, { backgroundColor: theme.card, borderColor: theme.border }]}
      >
        <Skeleton height={20} width={144} />
        <Skeleton height={160} />
        <View style={styles.loadingAction}>
          <Skeleton height={40} width={120} />
        </View>
      </View>
      <Text role="status" style={styles.srOnly}>
        글쓰기 화면을 불러오는 중입니다.
      </Text>
    </>
  );
}

function ComposeStateCard({
  alert = false,
  description,
  onAction,
  title,
}: {
  alert?: boolean;
  description: string;
  onAction: () => void;
  title: string;
}) {
  const theme = useTheme();

  return (
    <View
      accessibilityRole={alert ? 'alert' : undefined}
      style={[styles.stateCard, { backgroundColor: theme.card, borderColor: theme.border }]}
    >
      <Text style={[styles.stateTitle, { color: theme.text }]}>{title}</Text>
      <Text style={[styles.stateDescription, { color: theme.textSecondary }]}>{description}</Text>
      <View style={styles.stateAction}>
        <Button onPress={onAction} tone="secondary">
          {alert ? '다시 시도' : '홈으로 이동'}
        </Button>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flexGrow: 1,
    width: '100%',
  },
  content: {
    alignSelf: 'center',
    flexGrow: 1,
    gap: 20,
    maxWidth: 624,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xxl,
    width: '100%',
  },
  loadingCard: {
    borderRadius: radii.sm,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.lg,
  },
  loadingAction: { alignItems: 'flex-end' },
  stateCard: {
    borderRadius: radii.sm,
    borderWidth: 1,
    padding: 20,
  },
  stateTitle: { fontFamily: 'SUIT', fontWeight: '700', ...typography.md },
  stateDescription: { fontFamily: 'SUIT', marginTop: spacing.xs, ...typography.sm },
  stateAction: { alignItems: 'flex-start', marginTop: spacing.lg },
  srOnly: { height: 1, opacity: 0, overflow: 'hidden', position: 'absolute', width: 1 },
});
